# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19f3a4dd38ec78ef5dd51118a1e384c9a9868b4a5bb54e205779c28c409baebc00b25f6f2dd9871be7eb693fbff2dd8075d634442d60290933aee962b9e58ec

test:
  secret_key_base: 3bff9354e70d0ed46e03876983f6cf424ab1f46de42725ea263c3a9b68e990b84ef27ffee50233069f17014d9921a41e7e410a3971e921655bf5719dee82ad73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
